# Merge

In [21]:
import pandas as pd
var1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
var2 = pd.DataFrame({"A":[1,2,3,5], "C":[21,22,23,24]})

pd.merge(var1,var2, on="A")

   A   B   C
0  1  11  21
1  2  12  22
2  3  13  23

In [28]:
var3 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
var4 = pd.DataFrame({"A":[1,2,3,5], "C":[21,22,23,24]})

# pd.merge(var3,var4, how= "inner")
# pd.merge(var3,var4, how= "outer")
# pd.merge(var3,var4, how= "left")
# pd.merge(var3,var4, how= "right")
# pd.merge(var3,var4, how= "outer", indicator=True)
pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("Name","ID"))

   AName   B  AID   C
0      1  11    1  21
1      2  12    2  22
2      3  13    3  23
3      4  14    5  24

In [29]:
var3 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
var4 = pd.DataFrame({"A":[1,2,3,5], "B":[21,22,23,24]})

pd.merge(var3,var4,left_index=True,right_index=True,suffixes=("Name","ID"))

   AName  BName  AID  BID
0      1     11    1   21
1      2     12    2   22
2      3     13    3   23
3      4     14    5   24

# Concat

In [33]:
sr1=pd.Series([1,2,3,4])
sr2=pd.Series([21,31,41,51])
pd.concat([sr1,sr2])

0     1
1     2
2     3
3     4
0    21
1    31
2    41
3    51
dtype: int64

In [36]:
d1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2,3,5], "B":[21,22,23,24]})

# pd.concat([d1,d2])
pd.concat([d1,d2],axis=1) #According to column merge

   A   B  A   B
0  1  11  1  21
1  2  12  2  22
2  3  13  3  23
3  4  14  5  24

In [39]:
d1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2], "B":[21,22]})
# pd.concat([d1,d2],axis=1,join="outer")
pd.concat([d1,d2],axis=1,join="inner")

   A   B  A   B
0  1  11  1  21
1  2  12  2  22

In [42]:
d1 = pd.DataFrame({"A":[1,2,3,4], "B":[11,12,13,14]})
d2 = pd.DataFrame({"A":[1,2,3,4], "B":[21,22,23,24]})
# pd.concat([d1,d2],axis=1,join="outer")
pd.concat([d1,d2],axis=0,keys=["d1","d2"])

      A   B
d1 0  1  11
   1  2  12
   2  3  13
   3  4  14
d2 0  1  21
   1  2  22
   2  3  23
   3  4  24

In [44]:
d1 = pd.DataFrame({"D":[1,2,3,4]})
d2 = pd.DataFrame({"A":[1,2,3,4], "B":[21,22,23,24]})

pd.concat([d1,d2])

     D    A     B
0  1.0  NaN   NaN
1  2.0  NaN   NaN
2  3.0  NaN   NaN
3  4.0  NaN   NaN
0  NaN  1.0  21.0
1  NaN  2.0  22.0
2  NaN  3.0  23.0
3  NaN  4.0  24.0