In [6]:
import pandas as pd
csv = pd.read_csv("sales.csv")
csv

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status
0,1001,Aarav Sharma,Electronics,Laptop,1,55000,2026-01-05,Mumbai,Online,Completed
1,1002,Priya Patil,Home,Office Chair,2,6500,2026-01-07,Pune,Store,Completed
2,1003,Rohan Mehta,Electronics,Wireless Mouse,3,850,2026-01-09,Nashik,Online,Completed
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Store,Completed
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Online,Returned
5,1006,Ananya Desai,Electronics,Keyboard,1,1800,2026-01-14,Pune,Online,Completed
6,1007,Kabir Shah,Stationery,Printer Paper,4,320,2026-01-15,Nashik,Store,Completed
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Online,Cancelled
8,1009,Dev Malhotra,Electronics,Monitor,2,12500,2026-01-20,Mumbai,Store,Completed
9,1010,Meera Rao,Stationery,Pens Pack,6,180,2026-01-22,Pune,Online,Completed
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Online,Completed
11,1012,Kavya Iyer,Electronics,USB Drive,4,650,2026-02-03,Nashik,Store,Returned
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Online,Completed
13,1014,Tara Gupta,Home,Storage Box,3,450,2026-02-08,Pune,Store,Completed
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Online,Completed
15,1016,Sana Khan,Stationery,Sticky Notes,8,90,2026-02-12,Nashik,Online,Cancelled
16,1017,Yash Thakur,Home,Bookshelf,1,8200,2026-02-15,Mumbai,Store,Completed
17,1018,Diya More,Electronics,Webcam,1,2600,2026-02-18,Pune,Online,Completed
18,1019,Omkar Jadhav,Stationery,Notebook Pack,10,240,2026-02-20,Nagpur,Store,Completed
19,1020,Zoya Ali,Home,Office Chair,1,6900,2026-02-22,Nashik,Online,Returned
20,1021,Rahul Pawar,Electronics,Laptop,1,58000,2026-03-02,Mumbai,Store,Completed
21,1022,Pooja Sane,Stationery,Printer Paper,7,310,2026-03-05,Pune,Online,Completed
22,1023,Kunal Bhosale,Home,Desk Lamp,4,1150,2026-03-08,Aurangabad,Store,Completed
23,1024,Riya Chavan,Electronics,Monitor,1,12800,2026-03-12,Nashik,Online,Cancelled
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Online,Completed

In [13]:
csv.head(15)

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status
0,1001,Aarav Sharma,Electronics,Laptop,1,55000,2026-01-05,Mumbai,Online,Completed
1,1002,Priya Patil,Home,Office Chair,2,6500,2026-01-07,Pune,Store,Completed
2,1003,Rohan Mehta,Electronics,Wireless Mouse,3,850,2026-01-09,Nashik,Online,Completed
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Store,Completed
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Online,Returned
5,1006,Ananya Desai,Electronics,Keyboard,1,1800,2026-01-14,Pune,Online,Completed
6,1007,Kabir Shah,Stationery,Printer Paper,4,320,2026-01-15,Nashik,Store,Completed
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Online,Cancelled
8,1009,Dev Malhotra,Electronics,Monitor,2,12500,2026-01-20,Mumbai,Store,Completed
9,1010,Meera Rao,Stationery,Pens Pack,6,180,2026-01-22,Pune,Online,Completed
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Online,Completed
11,1012,Kavya Iyer,Electronics,USB Drive,4,650,2026-02-03,Nashik,Store,Returned
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Online,Completed
13,1014,Tara Gupta,Home,Storage Box,3,450,2026-02-08,Pune,Store,Completed
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Online,Completed

In [9]:
csv.tail(2)

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status
23,1024,Riya Chavan,Electronics,Monitor,1,12800,2026-03-12,Nashik,Online,Cancelled
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Online,Completed

In [16]:
csv.describe()

          order_id   quantity  unit_price_inr
count    25.000000  25.000000       25.000000
mean   1013.000000   3.360000     7714.600000
std       7.359801   3.080584    15219.208526
min    1001.000000   1.000000       90.000000
25%    1007.000000   1.000000      320.000000
50%    1013.000000   2.000000     1800.000000
75%    1019.000000   4.000000     7800.000000
max    1025.000000  12.000000    58000.000000

In [15]:
csv.describe(include="all")

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status
count,25.000000,25,25,25,25.000000,25.000000,25,25,25,25
unique,NaN,25,3,17,NaN,NaN,25,5,2,3
top,NaN,Aarav Sharma,Electronics,Laptop,NaN,NaN,2026-01-05,Mumbai,Online,Completed
freq,NaN,1,9,2,NaN,NaN,1,7,15,19
mean,1013.000000,NaN,NaN,NaN,3.360000,7714.600000,NaN,NaN,NaN,NaN
std,7.359801,NaN,NaN,NaN,3.080584,15219.208526,NaN,NaN,NaN,NaN
min,1001.000000,NaN,NaN,NaN,1.000000,90.000000,NaN,NaN,NaN,NaN
25%,1007.000000,NaN,NaN,NaN,1.000000,320.000000,NaN,NaN,NaN,NaN
50%,1013.000000,NaN,NaN,NaN,2.000000,1800.000000,NaN,NaN,NaN,NaN
75%,1019.000000,NaN,NaN,NaN,4.000000,7800.000000,NaN,NaN,NaN,NaN
max,1025.000000,NaN,NaN,NaN,12.000000,58000.000000,NaN,NaN,NaN,NaN

In [28]:
csv.index

RangeIndex(start=0, stop=25, step=1)

In [31]:
csv.columns

Index(['order_id', 'customer_name', 'category', 'product', 'quantity',
       'unit_price_inr', 'order_date', 'city', 'sales_channel',
       'order_status'],
      dtype='str')

In [41]:
csv[["customer_name","order_id"]]

     customer_name  order_id
0     Aarav Sharma      1001
1      Priya Patil      1002
2      Rohan Mehta      1003
3   Sneha Kulkarni      1004
4     Vikram Joshi      1005
5     Ananya Desai      1006
6       Kabir Shah      1007
7        Isha Nair      1008
8     Dev Malhotra      1009
9        Meera Rao      1010
10    Aditya Verma      1011
11      Kavya Iyer      1012
12     Arjun Singh      1013
13      Tara Gupta      1014
14  Neil Fernandes      1015
15       Sana Khan      1016
16     Yash Thakur      1017
17       Diya More      1018
18    Omkar Jadhav      1019
19        Zoya Ali      1020
20     Rahul Pawar      1021
21      Pooja Sane      1022
22   Kunal Bhosale      1023
23     Riya Chavan      1024
24  Manav Kulkarni      1025

In [57]:
csv[10:25:2]

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Online,Completed
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Online,Completed
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Online,Completed
16,1017,Yash Thakur,Home,Bookshelf,1,8200,2026-02-15,Mumbai,Store,Completed
18,1019,Omkar Jadhav,Stationery,Notebook Pack,10,240,2026-02-20,Nagpur,Store,Completed
20,1021,Rahul Pawar,Electronics,Laptop,1,58000,2026-03-02,Mumbai,Store,Completed
22,1023,Kunal Bhosale,Home,Desk Lamp,4,1150,2026-03-08,Aurangabad,Store,Completed
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Online,Completed

In [58]:
csv.index.array

<NumpyExtensionArray>
[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
 19, 20, 21, 22, 23, 24]
Length: 25, dtype: int64

In [61]:
import numpy as np
csv.to_numpy()

array([[1001, 'Aarav Sharma', 'Electronics', 'Laptop', 1, 55000,
        '2026-01-05', 'Mumbai', 'Online', 'Completed'],
       [1002, 'Priya Patil', 'Home', 'Office Chair', 2, 6500,
        '2026-01-07', 'Pune', 'Store', 'Completed'],
       [1003, 'Rohan Mehta', 'Electronics', 'Wireless Mouse', 3, 850,
        '2026-01-09', 'Nashik', 'Online', 'Completed'],
       [1004, 'Sneha Kulkarni', 'Stationery', 'Notebook Pack', 5, 250,
        '2026-01-10', 'Nagpur', 'Store', 'Completed'],
       [1005, 'Vikram Joshi', 'Home', 'Desk Lamp', 2, 1200, '2026-01-12',
        'Mumbai', 'Online', 'Returned'],
       [1006, 'Ananya Desai', 'Electronics', 'Keyboard', 1, 1800,
        '2026-01-14', 'Pune', 'Online', 'Completed'],
       [1007, 'Kabir Shah', 'Stationery', 'Printer Paper', 4, 320,
        '2026-01-15', 'Nashik', 'Store', 'Completed'],
       [1008, 'Isha Nair', 'Home', 'Bookshelf', 1, 7800, '2026-01-18',
        'Aurangabad', 'Online', 'Cancelled'],
       [1009, 'Dev Malhotra', 'Electronics', 'Monitor', 2, 12500,
        '2026-01-20', 'Mumbai', 'Store', 'Completed'],
       [1010, 'Meera Rao', 'Stationery', 'Pens Pack', 6, 180,
        '2026-01-22', 'Pune', 'Online', 'Completed'],
       [1011, 'Aditya Verma', 'Home', 'Study Table', 1, 9500,
        '2026-02-01', 'Nagpur', 'Online', 'Completed'],
       [1012, 'Kavya Iyer', 'Electronics', 'USB Drive', 4, 650,
        '2026-02-03', 'Nashik', 'Store', 'Returned'],
       [1013, 'Arjun Singh', 'Stationery', 'Whiteboard', 1, 2200,
        '2026-02-05', 'Mumbai', 'Online', 'Completed'],
       [1014, 'Tara Gupta', 'Home', 'Storage Box', 3, 450, '2026-02-08',
        'Pune', 'Store', 'Completed'],
       [1015, 'Neil Fernandes', 'Electronics', 'Headphones', 2, 3200,
        '2026-02-10', 'Aurangabad', 'Online', 'Completed'],
       [1016, 'Sana Khan', 'Stationery', 'Sticky Notes', 8, 90,
        '2026-02-12', 'Nashik', 'Online', 'Cancelled'],
       [1017, 'Yash Thakur', 'Home', 'Bookshelf', 1, 8200, '2026-02-15',
        'Mumbai', 'Store', 'Completed'],
       [1018, 'Diya More', 'Electronics', 'Webcam', 1, 2600,
        '2026-02-18', 'Pune', 'Online', 'Completed'],
       [1019, 'Omkar Jadhav', 'Stationery', 'Notebook Pack', 10, 240,
        '2026-02-20', 'Nagpur', 'Store', 'Completed'],
       [1020, 'Zoya Ali', 'Home', 'Office Chair', 1, 6900, '2026-02-22',
        'Nashik', 'Online', 'Returned'],
       [1021, 'Rahul Pawar', 'Electronics', 'Laptop', 1, 58000,
        '2026-03-02', 'Mumbai', 'Store', 'Completed'],
       [1022, 'Pooja Sane', 'Stationery', 'Printer Paper', 7, 310,
        '2026-03-05', 'Pune', 'Online', 'Completed'],
       [1023, 'Kunal Bhosale', 'Home', 'Desk Lamp', 4, 1150,
        '2026-03-08', 'Aurangabad', 'Store', 'Completed'],
       [1024, 'Riya Chavan', 'Electronics', 'Monitor', 1, 12800,
        '2026-03-12', 'Nashik', 'Online', 'Cancelled'],
       [1025, 'Manav Kulkarni', 'Stationery', 'Pens Pack', 12, 175,
        '2026-03-15', 'Mumbai', 'Online', 'Completed']], dtype=object)

In [67]:
v= np.asarray(csv)
v

array([[1001, 'Aarav Sharma', 'Electronics', 'Laptop', 1, 55000,
        '2026-01-05', 'Mumbai', 'Online', 'Completed'],
       [1002, 'Priya Patil', 'Home', 'Office Chair', 2, 6500,
        '2026-01-07', 'Pune', 'Store', 'Completed'],
       [1003, 'Rohan Mehta', 'Electronics', 'Wireless Mouse', 3, 850,
        '2026-01-09', 'Nashik', 'Online', 'Completed'],
       [1004, 'Sneha Kulkarni', 'Stationery', 'Notebook Pack', 5, 250,
        '2026-01-10', 'Nagpur', 'Store', 'Completed'],
       [1005, 'Vikram Joshi', 'Home', 'Desk Lamp', 2, 1200, '2026-01-12',
        'Mumbai', 'Online', 'Returned'],
       [1006, 'Ananya Desai', 'Electronics', 'Keyboard', 1, 1800,
        '2026-01-14', 'Pune', 'Online', 'Completed'],
       [1007, 'Kabir Shah', 'Stationery', 'Printer Paper', 4, 320,
        '2026-01-15', 'Nashik', 'Store', 'Completed'],
       [1008, 'Isha Nair', 'Home', 'Bookshelf', 1, 7800, '2026-01-18',
        'Aurangabad', 'Online', 'Cancelled'],
       [1009, 'Dev Malhotra', 'Electronics', 'Monitor', 2, 12500,
        '2026-01-20', 'Mumbai', 'Store', 'Completed'],
       [1010, 'Meera Rao', 'Stationery', 'Pens Pack', 6, 180,
        '2026-01-22', 'Pune', 'Online', 'Completed'],
       [1011, 'Aditya Verma', 'Home', 'Study Table', 1, 9500,
        '2026-02-01', 'Nagpur', 'Online', 'Completed'],
       [1012, 'Kavya Iyer', 'Electronics', 'USB Drive', 4, 650,
        '2026-02-03', 'Nashik', 'Store', 'Returned'],
       [1013, 'Arjun Singh', 'Stationery', 'Whiteboard', 1, 2200,
        '2026-02-05', 'Mumbai', 'Online', 'Completed'],
       [1014, 'Tara Gupta', 'Home', 'Storage Box', 3, 450, '2026-02-08',
        'Pune', 'Store', 'Completed'],
       [1015, 'Neil Fernandes', 'Electronics', 'Headphones', 2, 3200,
        '2026-02-10', 'Aurangabad', 'Online', 'Completed'],
       [1016, 'Sana Khan', 'Stationery', 'Sticky Notes', 8, 90,
        '2026-02-12', 'Nashik', 'Online', 'Cancelled'],
       [1017, 'Yash Thakur', 'Home', 'Bookshelf', 1, 8200, '2026-02-15',
        'Mumbai', 'Store', 'Completed'],
       [1018, 'Diya More', 'Electronics', 'Webcam', 1, 2600,
        '2026-02-18', 'Pune', 'Online', 'Completed'],
       [1019, 'Omkar Jadhav', 'Stationery', 'Notebook Pack', 10, 240,
        '2026-02-20', 'Nagpur', 'Store', 'Completed'],
       [1020, 'Zoya Ali', 'Home', 'Office Chair', 1, 6900, '2026-02-22',
        'Nashik', 'Online', 'Returned'],
       [1021, 'Rahul Pawar', 'Electronics', 'Laptop', 1, 58000,
        '2026-03-02', 'Mumbai', 'Store', 'Completed'],
       [1022, 'Pooja Sane', 'Stationery', 'Printer Paper', 7, 310,
        '2026-03-05', 'Pune', 'Online', 'Completed'],
       [1023, 'Kunal Bhosale', 'Home', 'Desk Lamp', 4, 1150,
        '2026-03-08', 'Aurangabad', 'Store', 'Completed'],
       [1024, 'Riya Chavan', 'Electronics', 'Monitor', 1, 12800,
        '2026-03-12', 'Nashik', 'Online', 'Cancelled'],
       [1025, 'Manav Kulkarni', 'Stationery', 'Pens Pack', 12, 175,
        '2026-03-15', 'Mumbai', 'Online', 'Completed']], dtype=object)

In [71]:
csv.sort_index(ascending=True,axis=1)

,category,city,customer_name,order_date,order_id,order_status,product,quantity,sales_channel,unit_price_inr
0,Electronics,Mumbai,Aarav Sharma,2026-01-05,1001,Completed,Laptop,1,Online,55000
1,Home,Pune,Priya Patil,2026-01-07,1002,Completed,Office Chair,2,Store,6500
2,Electronics,Nashik,Rohan Mehta,2026-01-09,1003,Completed,Wireless Mouse,3,Online,850
3,Stationery,Nagpur,Sneha Kulkarni,2026-01-10,1004,Completed,Notebook Pack,5,Store,250
4,Home,Mumbai,Vikram Joshi,2026-01-12,1005,Returned,Desk Lamp,2,Online,1200
5,Electronics,Pune,Ananya Desai,2026-01-14,1006,Completed,Keyboard,1,Online,1800
6,Stationery,Nashik,Kabir Shah,2026-01-15,1007,Completed,Printer Paper,4,Store,320
7,Home,Aurangabad,Isha Nair,2026-01-18,1008,Cancelled,Bookshelf,1,Online,7800
8,Electronics,Mumbai,Dev Malhotra,2026-01-20,1009,Completed,Monitor,2,Store,12500
9,Stationery,Pune,Meera Rao,2026-01-22,1010,Completed,Pens Pack,6,Online,180
10,Home,Nagpur,Aditya Verma,2026-02-01,1011,Completed,Study Table,1,Online,9500
11,Electronics,Nashik,Kavya Iyer,2026-02-03,1012,Returned,USB Drive,4,Store,650
12,Stationery,Mumbai,Arjun Singh,2026-02-05,1013,Completed,Whiteboard,1,Online,2200
13,Home,Pune,Tara Gupta,2026-02-08,1014,Completed,Storage Box,3,Store,450
14,Electronics,Aurangabad,Neil Fernandes,2026-02-10,1015,Completed,Headphones,2,Online,3200
15,Stationery,Nashik,Sana Khan,2026-02-12,1016,Cancelled,Sticky Notes,8,Online,90
16,Home,Mumbai,Yash Thakur,2026-02-15,1017,Completed,Bookshelf,1,Store,8200
17,Electronics,Pune,Diya More,2026-02-18,1018,Completed,Webcam,1,Online,2600
18,Stationery,Nagpur,Omkar Jadhav,2026-02-20,1019,Completed,Notebook Pack,10,Store,240
19,Home,Nashik,Zoya Ali,2026-02-22,1020,Returned,Office Chair,1,Online,6900
20,Electronics,Mumbai,Rahul Pawar,2026-03-02,1021,Completed,Laptop,1,Store,58000
21,Stationery,Pune,Pooja Sane,2026-03-05,1022,Completed,Printer Paper,7,Online,310
22,Home,Aurangabad,Kunal Bhosale,2026-03-08,1023,Completed,Desk Lamp,4,Store,1150
23,Electronics,Nashik,Riya Chavan,2026-03-12,1024,Cancelled,Monitor,1,Online,12800
24,Stationery,Mumbai,Manav Kulkarni,2026-03-15,1025,Completed,Pens Pack,12,Online,175

In [134]:
csv.loc[0,["category"]]="Home"
csv

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status,4,categorycity
0,1001,Aarav Sharma,Home,Laptop,1,55000,2026-01-05,Home,Online,Completed,4.0,Home
1,1002,Priya Patil,Home,Office Chair,2,6500,2026-01-07,Pune,Store,Completed,NaN,NaN
2,1003,Rohan Mehta,Electronics,Wireless Mouse,3,850,2026-01-09,Nashik,Online,Completed,NaN,NaN
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Store,Completed,NaN,NaN
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Online,Returned,NaN,NaN
5,1006,Ananya Desai,Electronics,Keyboard,1,1800,2026-01-14,Pune,Online,Completed,NaN,NaN
6,1007,Kabir Shah,Stationery,Printer Paper,4,320,2026-01-15,Nashik,Store,Completed,NaN,NaN
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Online,Cancelled,NaN,NaN
8,1009,Dev Malhotra,Electronics,Monitor,2,12500,2026-01-20,Mumbai,Store,Completed,NaN,NaN
9,1010,Meera Rao,Stationery,Pens Pack,6,180,2026-01-22,Pune,Online,Completed,NaN,NaN
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Online,Completed,NaN,NaN
11,1012,Kavya Iyer,Electronics,USB Drive,4,650,2026-02-03,Nashik,Store,Returned,NaN,NaN
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Online,Completed,NaN,NaN
13,1014,Tara Gupta,Home,Storage Box,3,450,2026-02-08,Pune,Store,Completed,NaN,NaN
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Online,Completed,NaN,NaN
15,1016,Sana Khan,Stationery,Sticky Notes,8,90,2026-02-12,Nashik,Online,Cancelled,NaN,NaN
16,1017,Yash Thakur,Home,Bookshelf,1,8200,2026-02-15,Mumbai,Store,Completed,NaN,NaN
17,1018,Diya More,Electronics,Webcam,1,2600,2026-02-18,Pune,Online,Completed,NaN,NaN
18,1019,Omkar Jadhav,Stationery,Notebook Pack,10,240,2026-02-20,Nagpur,Store,Completed,NaN,NaN
19,1020,Zoya Ali,Home,Office Chair,1,6900,2026-02-22,Nashik,Online,Returned,NaN,NaN
20,1021,Rahul Pawar,Electronics,Laptop,1,58000,2026-03-02,Mumbai,Store,Completed,NaN,NaN
21,1022,Pooja Sane,Stationery,Printer Paper,7,310,2026-03-05,Pune,Online,Completed,NaN,NaN
22,1023,Kunal Bhosale,Home,Desk Lamp,4,1150,2026-03-08,Aurangabad,Store,Completed,NaN,NaN
23,1024,Riya Chavan,Electronics,Monitor,1,12800,2026-03-12,Nashik,Online,Cancelled,NaN,NaN
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Online,Completed,NaN,NaN

In [132]:
csv.loc[(csv["order_status"]=="Cancelled")]

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status,4,categorycity
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Online,Cancelled,NaN,NaN
15,1016,Sana Khan,Stationery,Sticky Notes,8,90,2026-02-12,Nashik,Online,Cancelled,NaN,NaN
23,1024,Riya Chavan,Electronics,Monitor,1,12800,2026-03-12,Nashik,Online,Cancelled,NaN,NaN

In [121]:
csv.loc[4,["customer_name","category"]]

customer_name    Vikram Joshi
category                 Home
Name: 4, dtype: str

In [129]:
csv.loc[[3,4],:]

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status,4,categorycity
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Store,Completed,NaN,NaN
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Online,Returned,NaN,NaN

In [136]:
csv.iloc[0,2]

'Home'

In [138]:
csv.drop("sales_channel",axis=1)

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,order_status,4,categorycity
0,1001,Aarav Sharma,Home,Laptop,1,55000,2026-01-05,Home,Completed,4.0,Home
1,1002,Priya Patil,Home,Office Chair,2,6500,2026-01-07,Pune,Completed,NaN,NaN
2,1003,Rohan Mehta,Electronics,Wireless Mouse,3,850,2026-01-09,Nashik,Completed,NaN,NaN
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Completed,NaN,NaN
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Returned,NaN,NaN
5,1006,Ananya Desai,Electronics,Keyboard,1,1800,2026-01-14,Pune,Completed,NaN,NaN
6,1007,Kabir Shah,Stationery,Printer Paper,4,320,2026-01-15,Nashik,Completed,NaN,NaN
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Cancelled,NaN,NaN
8,1009,Dev Malhotra,Electronics,Monitor,2,12500,2026-01-20,Mumbai,Completed,NaN,NaN
9,1010,Meera Rao,Stationery,Pens Pack,6,180,2026-01-22,Pune,Completed,NaN,NaN
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Completed,NaN,NaN
11,1012,Kavya Iyer,Electronics,USB Drive,4,650,2026-02-03,Nashik,Returned,NaN,NaN
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Completed,NaN,NaN
13,1014,Tara Gupta,Home,Storage Box,3,450,2026-02-08,Pune,Completed,NaN,NaN
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Completed,NaN,NaN
15,1016,Sana Khan,Stationery,Sticky Notes,8,90,2026-02-12,Nashik,Cancelled,NaN,NaN
16,1017,Yash Thakur,Home,Bookshelf,1,8200,2026-02-15,Mumbai,Completed,NaN,NaN
17,1018,Diya More,Electronics,Webcam,1,2600,2026-02-18,Pune,Completed,NaN,NaN
18,1019,Omkar Jadhav,Stationery,Notebook Pack,10,240,2026-02-20,Nagpur,Completed,NaN,NaN
19,1020,Zoya Ali,Home,Office Chair,1,6900,2026-02-22,Nashik,Returned,NaN,NaN
20,1021,Rahul Pawar,Electronics,Laptop,1,58000,2026-03-02,Mumbai,Completed,NaN,NaN
21,1022,Pooja Sane,Stationery,Printer Paper,7,310,2026-03-05,Pune,Completed,NaN,NaN
22,1023,Kunal Bhosale,Home,Desk Lamp,4,1150,2026-03-08,Aurangabad,Completed,NaN,NaN
23,1024,Riya Chavan,Electronics,Monitor,1,12800,2026-03-12,Nashik,Cancelled,NaN,NaN
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Completed,NaN,NaN

In [141]:
csv.drop(23,axis=0)

,order_id,customer_name,category,product,quantity,unit_price_inr,order_date,city,sales_channel,order_status,4,categorycity
0,1001,Aarav Sharma,Home,Laptop,1,55000,2026-01-05,Home,Online,Completed,4.0,Home
1,1002,Priya Patil,Home,Office Chair,2,6500,2026-01-07,Pune,Store,Completed,NaN,NaN
2,1003,Rohan Mehta,Electronics,Wireless Mouse,3,850,2026-01-09,Nashik,Online,Completed,NaN,NaN
3,1004,Sneha Kulkarni,Stationery,Notebook Pack,5,250,2026-01-10,Nagpur,Store,Completed,NaN,NaN
4,1005,Vikram Joshi,Home,Desk Lamp,2,1200,2026-01-12,Mumbai,Online,Returned,NaN,NaN
5,1006,Ananya Desai,Electronics,Keyboard,1,1800,2026-01-14,Pune,Online,Completed,NaN,NaN
6,1007,Kabir Shah,Stationery,Printer Paper,4,320,2026-01-15,Nashik,Store,Completed,NaN,NaN
7,1008,Isha Nair,Home,Bookshelf,1,7800,2026-01-18,Aurangabad,Online,Cancelled,NaN,NaN
8,1009,Dev Malhotra,Electronics,Monitor,2,12500,2026-01-20,Mumbai,Store,Completed,NaN,NaN
9,1010,Meera Rao,Stationery,Pens Pack,6,180,2026-01-22,Pune,Online,Completed,NaN,NaN
10,1011,Aditya Verma,Home,Study Table,1,9500,2026-02-01,Nagpur,Online,Completed,NaN,NaN
11,1012,Kavya Iyer,Electronics,USB Drive,4,650,2026-02-03,Nashik,Store,Returned,NaN,NaN
12,1013,Arjun Singh,Stationery,Whiteboard,1,2200,2026-02-05,Mumbai,Online,Completed,NaN,NaN
13,1014,Tara Gupta,Home,Storage Box,3,450,2026-02-08,Pune,Store,Completed,NaN,NaN
14,1015,Neil Fernandes,Electronics,Headphones,2,3200,2026-02-10,Aurangabad,Online,Completed,NaN,NaN
15,1016,Sana Khan,Stationery,Sticky Notes,8,90,2026-02-12,Nashik,Online,Cancelled,NaN,NaN
16,1017,Yash Thakur,Home,Bookshelf,1,8200,2026-02-15,Mumbai,Store,Completed,NaN,NaN
17,1018,Diya More,Electronics,Webcam,1,2600,2026-02-18,Pune,Online,Completed,NaN,NaN
18,1019,Omkar Jadhav,Stationery,Notebook Pack,10,240,2026-02-20,Nagpur,Store,Completed,NaN,NaN
19,1020,Zoya Ali,Home,Office Chair,1,6900,2026-02-22,Nashik,Online,Returned,NaN,NaN
20,1021,Rahul Pawar,Electronics,Laptop,1,58000,2026-03-02,Mumbai,Store,Completed,NaN,NaN
21,1022,Pooja Sane,Stationery,Printer Paper,7,310,2026-03-05,Pune,Online,Completed,NaN,NaN
22,1023,Kunal Bhosale,Home,Desk Lamp,4,1150,2026-03-08,Aurangabad,Store,Completed,NaN,NaN
24,1025,Manav Kulkarni,Stationery,Pens Pack,12,175,2026-03-15,Mumbai,Online,Completed,NaN,NaN