# Pandas Notes: Creating, Inserting, and Removing DataFrame Columns

These notes cover `pd.DataFrame()`, `DataFrame.insert()`, `DataFrame.pop()`, and Python's `del` statement.

## Learning objectives
- Create a DataFrame from a dictionary.
- Insert new columns at specific positions.
- Remove a column and keep its values with `pop()`.
- Delete a column with `del`.
- Understand the difference between these operations.

> **Setup:** If Pandas is not installed, run `!pip install pandas` in a notebook cell.

## 1. Import Pandas

Pandas is a Python library used to work with tabular data. Its common alias is `pd`.

**Syntax**
```python
import pandas as pd
```

In [2]:
import pandas as pd

## 2. Create a DataFrame with `pd.DataFrame()`

A **DataFrame** is a two-dimensional, table-like structure with rows and columns.

**Syntax**
```python
pd.DataFrame(data, index=None, columns=None)
```

- A dictionary's keys become column names.
- The dictionary's lists become column values.
- Lists used as columns should have the same length.
- Pandas creates a default row index starting at `0` when no index is supplied.

In [3]:
var = pd.DataFrame({"A": [1, 2, 3, 4], "D": [5, 5, 6, 7]})
var

   A  D
0  1  5
1  2  5
2  3  6
3  4  7

### Explanation

- `var` is the variable holding the DataFrame.
- `"A"` and `"D"` are column labels.
- `0`, `1`, `2`, and `3` are the default index labels.

## 3. Insert a column with `DataFrame.insert()`

`insert()` adds a new column at a specified position in the existing DataFrame.

**Syntax**
```python
dataframe.insert(loc, column, value, allow_duplicates=False)
```

| Parameter | Meaning |
|---|---|
| `loc` | Integer position where the column should be inserted. Positions start at `0`. |
| `column` | Name of the new column. |
| `value` | Column values, such as a list, Series, or scalar. |
| `allow_duplicates` | Whether duplicate column labels are allowed; defaults to `False`. |

**Important:** `insert()` changes the DataFrame in place and returns `None`. Do not assign its result back to the DataFrame.

### 3.1 Insert column B using an existing column

Here, `var["A"]` selects column A as a Series. Its values are used for the new column B.

In [4]:
var.insert(1, "B", var["A"])
var

   A  B  D
0  1  1  5
1  2  2  5
2  3  3  6
3  4  4  7

**Explanation**
- `1` means position 1, the second column.
- `"B"` is the new column name.
- `var["A"]` supplies the values for column B.
- The column order is now `A`, `B`, `D`.

### 3.2 Insert column C using a list

The list supplies one value for each row in this DataFrame.

In [5]:
var.insert(2, "C", [10, 11, 12, 13])
var

   A  B   C  D
0  1  1  10  5
1  2  2  11  5
2  3  3  12  6
3  4  4  13  7

**Explanation**
- `2` means position 2, the third column.
- The new column C contains `10`, `11`, `12`, and `13`.
- The column order is now `A`, `B`, `C`, `D`.

**Common error:** If a list has a length that does not match the number of rows, Pandas raises a `ValueError`.

## 4. Remove and return a column with `DataFrame.pop()`

`pop()` removes a column from the DataFrame and returns that column as a Pandas Series.

**Syntax**
```python
removed_column = dataframe.pop("column_name")
```

- The original DataFrame is changed.
- The returned Series can be saved and used separately.
- The Series retains the column's name and index.
- If the column does not exist, Pandas raises a `KeyError`.

In [6]:
var1 = var.pop("C")
var1

0    10
1    11
2    12
3    13
Name: C, dtype: int64

The removed column is now stored in `var1`. Check the original DataFrame to see that column C is no longer present.

In [7]:
var

   A  B  D
0  1  1  5
1  2  2  5
2  3  3  6
3  4  4  7

## 5. Delete a column with `del`

`del` is a Python statement (not a Pandas method) that removes a column from a DataFrame.

**Syntax**
```python
del dataframe["column_name"]
```

- It modifies the original DataFrame.
- It does not return the removed column's values.
- If the named column does not exist, a `KeyError` is raised.

In [8]:
del var["B"]
var

   A  D
0  1  5
1  2  5
2  3  6
3  4  7

## 6. Comparison: `insert()`, `pop()`, and `del`

| Operation | Purpose | Changes original DataFrame? | Returns column values? |
|---|---|---|---|
| `insert()` | Adds a column at a chosen position | Yes | No; returns `None` |
| `pop()` | Removes a column | Yes | Yes, as a Series |
| `del` | Removes a column | Yes | No |

**Tip:** If you want to save a column before deleting it, use `pop()` or make a copy first:
```python
saved_values = df["A"].copy()
del df["A"]
```

## 7. Useful DataFrame checks

These are handy while learning Pandas:

```python
var.columns  # Column labels
var.shape    # (number of rows, number of columns)
var.head()   # First five rows by default
var.info()   # Column names, non-null counts, and data types
```

## Official documentation
- [Pandas DataFrame](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html)
- [DataFrame.insert()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.insert.html)
- [DataFrame.pop()](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.pop.html)